# Generated by Django 3.2.7 on 2021-12-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irantourism', '0002_auto_20211230_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
