# Generated by Django 3.2.7 on 2022-01-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irantourism', '0003_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='irantourism.city'),
            preserve_default=False,
        ),
    ]
