# Generated by Django 3.2.7 on 2022-01-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irantourism', '0004_touristattraction_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelogue',
            name='is_visible',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
