# Generated by Django 3.2.7 on 2022-01-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irantourism', '0005_travelogue_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelogue',
            name='tourist_attraction',
        ),
    ]
